//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontLab.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string VIN { get; set; }
        public int Year { get; set; }
        public int MakeID { get; set; }
        public int MovieID { get; set; }
        public decimal DailyCost { get; set; }
        public int FuelTypeID { get; set; }
        public int StatusID { get; set; }
        public string Description { get; set; }
        public bool IsAutomatic { get; set; }
        public string Image { get; set; }
    
        public virtual FuelType FuelType { get; set; }
        public virtual Make Make { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
